services:

  db:
    image: mysql:8
    container_name: mysql-portfolio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Theo68150
      MYSQL_DATABASE: portfolio
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./backend
    image: backend-portfolio:latest
    container_name: backend-portfolio
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/local/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: sh -c "sleep 10 && node index.js"
  frontend:
    build:
      context: ./Frontend/portfolio
    image: frontend-portfolio:latest
    container_name: frontend-portfolio
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data: