CREATE TABLE IF NOT EXISTS portfolio.contacts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	mail VARCHAR(255) NOT NULL,
	message TEXT NOT NULL
);